# Description: This playbook will deploy ansible on a remote container

# needed provided variables:
# container_id

- name: upgrade
  import_tasks: tasks/proxmox/exec_container.yml
  vars:
    command: "apt-get update && apt-get upgrade -y"

- name: install_python
  import_tasks: tasks/proxmox/exec_container.yml
  vars:
    command: "apt-get install -y python3"


- name: install_ansible
  import_tasks: tasks/proxmox/exec_container.yml
  vars:
    command: "apt-get install -y ansible"

- name: install_pipx
  import_tasks: tasks/proxmox/exec_container.yml
  vars:
    command: "apt-get install -y pipx"

- name: install_winrm_plugin
  import_tasks: tasks/proxmox/exec_container.yml
  vars:
    command: "pipx install http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm --include-deps"