- name: configure vulerability asreproasting
  shell: >
    qm guest exec 111 -- powershell.exe -Command "
    Set-ADAccountControl -Identity 'svc-bella' -DoesNotRequirePreAuth \$true"
  register: configure_asreproasting
  until: configure_asreproasting.rc == 0
  retries: 50 
  delay: 5

- name: add dns forwarder
  shell: >
    qm guest exec 111 -- powershell.exe -Command "
    Add-DnsServerConditionalForwarderZone -Name 'mgmgrand.local' -MasterServers 10.100.0.112"
  register: configure_dns_forwarder_mgm
  until: configure_dns_forwarder_mgm.rc == 0
  retries: 50
  delay: 5

- name: add dns forwarder
  shell: >
    qm guest exec 112 -- powershell.exe -Command "
    Add-DnsServerConditionalForwarderZone -Name 'bellagio.local' -MasterServers 10.100.0.111"
  register: configure_dns_forwarder_bella
  until: configure_dns_forwarder_bella.rc == 0
  retries: 50
  delay: 5

- name: configure trust link
  shell: >
    qm guest exec 111 -- powershell.exe -Command "
    \$remoteContext = New-Object -TypeName 'System.DirectoryServices.ActiveDirectory.DirectoryContext' -ArgumentList @('Domain', 'mgmgrand.local', 'Administrator', 'Velizy78!');
    \$remoteDomain = [System.DirectoryServices.ActiveDirectory.Domain]::GetDomain(\$remoteContext);
    \$localDomain = [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain();
    \$localDomain.CreateTrustRelationship(\$remoteDomain, 'Outbound');
    "
  register: configure_trust_link
  until: configure_trust_link.rc == 0
  retries: 50
  delay: 5

- name: configure smb on server
  shell: 'qm guest exec 111 "powershell.exe" "D:\\111_smb.ps1"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10

- name: allow execute script on client
  shell: 'qm guest exec 211 "powershell.exe" "Set-ExecutionPolicy RemoteSigned"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10

- name: execute script on client scheduled task
  shell: 'qm guest exec 211 "powershell.exe" "D:\\211_client_scheduled_task.ps1"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10