- name: configure vulerability asreproasting
  shell: >
    qm guest exec 111 -- powershell.exe -Command "
    Set-ADAccountControl -Identity 'svc-bella' -DoesNotRequirePreAuth \$true"
  register: configure_asreproasting
  until: configure_asreproasting.rc == 0
  retries: 50 
  delay: 5

- name: add dns forwarder
  shell: >
    qm guest exec 111 -- powershell.exe -Command "
    Add-DnsServerConditionalForwarderZone -Name 'mgmgrand.local' -MasterServers 10.100.0.112"
  register: configure_dns_forwarder_mgm
  until: configure_dns_forwarder_mgm.rc == 0
  retries: 50
  delay: 5

- name: add dns forwarder
  shell: >
    qm guest exec 112 -- powershell.exe -Command "
    Add-DnsServerConditionalForwarderZone -Name 'bellagio.local' -MasterServers 10.100.0.111"
  register: configure_dns_forwarder_bella
  until: configure_dns_forwarder_bella.rc == 0
  retries: 50
  delay: 5

- name: configure trust link
  shell: >
    qm guest exec 111 -- powershell.exe -Command "
    \$remoteContext = New-Object -TypeName 'System.DirectoryServices.ActiveDirectory.DirectoryContext' -ArgumentList @('Domain', 'mgmgrand.local', 'Administrator', 'Velizy78!');
    \$remoteDomain = [System.DirectoryServices.ActiveDirectory.Domain]::GetDomain(\$remoteContext);
    \$localDomain = [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain();
    \$localDomain.CreateTrustRelationship(\$remoteDomain, 'Bidirectional');
    "
  register: configure_trust_link
  until: configure_trust_link.rc == 0
  retries: 50
  delay: 5


- name: Configure SMB on server
  shell: 'qm guest exec 111 "powershell.exe" "D:\\111_smb.ps1"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10


- name: allow execute script on client
  shell: 'qm guest exec 211 "powershell.exe" "Set-ExecutionPolicy RemoteSigned"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10

- name: allow execute script on client
  shell: 'qm guest exec 212 "powershell.exe" "Set-ExecutionPolicy RemoteSigned"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10

- name: configure winrm on client 211
  shell: 'qm guest exec 211 "powershell.exe" "Enable-PSRemoting -Force"'
  register: configure_winrm
  until: configure_winrm.rc == 0
  retries: 5
  delay: 10

- name: Allow svc-winrm access to WinRM on client 211
  shell: |
    qm guest exec 211 powershell.exe "Add-LocalGroupMember -Group 'Remote Management Users' -Member 'mgmgrand\svc-winrm'"
  register: configure_winrm
  until: configure_winrm.rc == 0
  retries: 5
  delay: 10


- name: execute script on client scheduled task
  shell: 'qm guest exec 211 "powershell.exe" "D:\\211_client_scheduled_task.ps1"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10

- name: execute script service file exe
  shell: 'qm guest exec 212 "powershell.exe" "D:\\212_client_service.ps1"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10

- name: execute script sysvol server 113
  shell: 'qm guest exec 212 "powershell.exe" "D:\\113_sysvol.ps1"'
  register: script_result
  until: script_result.rc == 0
  retries: 5
  delay: 10

# - name: create user local pc 212
#   shell: 'qm guest exec 212 "powershell.exe" "D:\\212_create_user.ps1"'
#   register: script_result
#   until: script_result.rc == 0
#   retries: 5
#   delay: 10

- name: Desactiver signature smb srv 113
  shell: |
    qm guest exec 113 powershell.exe "Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'RequireSecuritySignature' -Value 0"
  register: configure_smb_not_signed
  until: configure_smb_not_signed.rc == 0
  retries: 5
  delay: 10

- name: Desactiver signature smb srv 113
  shell: |
    qm guest exec 113 powershell.exe "Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters' -Name 'RequireSecuritySignature' -Value 0"
  register: configure_smb_not_signed
  until: configureconfigure_smb_not_signed.rc == 0
  retries: 5
  delay: 10

- name: confiruation signature smb srv 113 false
  shell: |
    qm guest exec 113 powershell.exe "Set-SmbServerConfiguration -EnableSecuritySignature \$false -Force"
  register: configure_smb_not_signed
  until: configureconfigure_smb_not_signed.rc == 0
  retries: 5
  delay: 10

- name: restart lanmanserver srv 113
  shell: |
    qm guest exec 113 powershell.exe "Restart-Service lanmanserver -force"
  register: restart_lanmanserver
  until: restart_lanmanserver.rc == 0
  retries: 5
  delay: 10

- name: configure rdp on client 211
  shell: |
    qm guest exec 211 powershell.exe "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name 'fDenyTSConnections' -Value 0"
  register: configure_rdp
  until: configure_rdp.rc == 0
  retries: 5
  delay: 10

- name: configure rdp on client 211
  shell: |
    qm guest exec 211 powershell.exe "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
  register: configure_rdp
  until: configure_rdp.rc == 0
  retries: 5
  delay: 10


