---
- name: Configure Trust Relationship
  hosts: win2012_1
  gather_facts: yes
  tasks:
    - name: Create trust with secondary domain
      win_shell: |
        $trustPassword = ConvertTo-SecureString -String "{{ trust_password }}" -AsPlainText -Force
        New-TrustRelationship -Name "SecondaryDomain" -TargetDomainName "secondary.local" -TrustDirection Bidirectional -TrustType Forest -TrustPassword $trustPassword
      register: trust_result
      failed_when: trust_result.rc != 0 and "already exists" not in trust_result.stderr

      