---
- name: Create Windows VMs on Proxmox
  hosts: proxmox
  gather_facts: no
  tasks:
    - name: Clone template to create Windows VMs
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ proxmox_password }}"
        api_host: "{{ ansible_host }}"
        name: "{{ item.vm_name }}"
        node: "{{ proxmox_node }}"
        clone: "{{ item.template }}"
        storage: "{{ proxmox_storage | default('local') }}"
        memory: "{{ item.memory }}"
        cores: "{{ item.cores }}"
        state: present
        timeout: 300
      loop: "{{ groups['windows_servers'] | map('extract', hostvars) | list }}"
    
    - name: Wait for VMs to be created
      pause:
        seconds: 30
    
    - name: Start Windows VMs
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ proxmox_password }}"
        api_host: "{{ ansible_host }}"
        name: "{{ item.vm_name }}"
        node: "{{ proxmox_node }}"
        state: started
      loop: "{{ groups['windows_servers'] | map('extract', hostvars) | list }}"
    
    - name: Wait for VMs to boot
      pause:
        minutes: 5