---
- name: Install Active Directory on Secondary Domain Controllers
  hosts: win2012_2:win2016
  gather_facts: yes
  tasks:
    - name: Install AD-Domain-Services feature
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes
        include_sub_features: yes
      register: ad_feature
    
    - name: Reboot after AD installation
      win_reboot:
        msg: "Rebooting after AD installation"
        pre_reboot_delay: 15
        post_reboot_delay: 60
      when: ad_feature.reboot_required
    
    - name: Join domain as domain controller
      win_domain_controller:
        dns_domain_name: corp.local
        domain_admin_user: Administrator@corp.local
        domain_admin_password: "{{ domain_admin_password }}"
        safe_mode_password: "{{ domain_safemode_password }}"
        state: domain_controller
      register: domain_install
    
    - name: Reboot after domain controller promotion
      win_reboot:
        msg: "Rebooting after domain controller promotion"
        pre_reboot_delay: 15
        post_reboot_delay: 90
      when: domain_install.reboot_required