- name: copy_docker_compose
  copy:
    src: ../dist/
    dest: /opt/2bgp-ad/
    remote_src: no
    mode: '0644'

- name: haproxy_config_fix
  shell: echo "" >> /opt/2bgp-ad/config/haproxy.cfg
  args:
    executable: /bin/bash
  register: haproxy_config_fix
  until: haproxy_config_fix is succeeded

- name: copy_backend_files
  copy:
    src: ../backend/
    dest: /opt/2bgp-ad/backend/
    remote_src: no
    mode: '0644'

- name: copy_frontend_files
  copy:
    src: ../frontend/
    dest: /opt/2bgp-ad/frontend/
    remote_src: no
    mode: '0644'

- name: create_backend_env_file
  copy:
    dest: /opt/2bgp-ad/config/backend.env
    content: |
      PORT=3000
      MONGODB_URI=mongodb://2bgp-ad:{{ web_mongo_password }}@mongodb/?retryWrites=true&w=majority
      JWT_SECRET={{ web_jwt_password}}
      ADMIN_SYSTEM_TOKEN={{ web_admin_deploy_token}}
      DEPLOYMENT_API_URL=http://{{ container_deployment_ip }}:5000
    mode: '0644'

- name: create_frontend_env_file
  copy:
    dest: /opt/2bgp-ad/config/frontend.env
    content: |
      REACT_APP_API_URL=http://{{ public_ct_hostname }}/api
    mode: '0644'

- name: create_mongodb_env_file
  copy:
    dest: /opt/2bgp-ad/config/mongodb.env
    content: |
      MONGO_INITDB_ROOT_USERNAME=2bgp-ad
      MONGO_INITDB_ROOT_PASSWORD={{ web_mongo_password }}
    mode: '0644'

- name: start_compose
  command: docker compose up -d
  args:
    chdir: /opt/2bgp-ad/
  register: compose_output
  timeout: 3000
  until: compose_output is succeeded