- name: install_gnupg
  import_tasks: ./apt_install.yml
  vars:
    apt_packages:
      - gnupg
      
- name: download_gpg
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: add_apt_repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present


- name: add_repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install_docker
  import_tasks: ./apt_install.yml
  vars:
    apt_packages:
      - docker-ce
