# Description: This tasks will install python3, ansible and pipx on the remote host.

- name: apt_update
  apt:
    update_cache: yes
    upgrade: yes

- name: install_python
  apt:
    name: python3
    state: present

- name: install_ansible
  apt:
    name: ansible
    state: present

- name: install_pipx
  apt:
    name: pipx
    state: present
