- name: install_gnupg
  import_tasks: ./apt_install.yml
  vars:
    apt_packages:
      - gnupg
      - curl
      
- name: keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: download
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc

- name: add_repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install_docker
  import_tasks: ./apt_install.yml
  vars:
    apt_packages:
      - docker-ce
