# Description: This tasks will install python3, ansible and pipx on the remote host.

- name: Upgrade system packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Python3
  apt:
    name: python3
    state: present

- name: Install Ansible
  apt:
    name: ansible
    state: present

- name: Install pipx
  apt:
    name: pipx
    state: present

- name: Install WinRM plugin
  pip:
    name: git+https://github.com/diyan/pywinrm.git#egg=pywinrm
    executable: pipx
