# This playbook deploys VMs in Proxmox based on a template.
# Needed variable:
# - client_id

- name: deploy_client
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  vars:
    - ansible_python_interpreter: /opt/deployment_api/venv/bin/python

  tasks:
    - name: set_fact
      import_tasks: tasks/set_fact.yml 

    - name: creating_deploy
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_ip }}:8006"
        clone: "vm-{{ client_id }}-{{ item.id }}"
        vmid: "{{ item.id }}"
        newid: "{{ client_id }}00{{ item.id }}"
        name: "vm-{{ client_id }}-{{ item.id }}"
        node: "{{ proxmox_node }}"
        storage: "{{ vm_storage }}"
        format: raw
        timeout: 600
      with_items: "{{ templates }}"
      async: 1200
      poll: 0
      register: deploy_jobs
