- name: deploy_client
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
    ansible_python_interpreter: /opt/deployment_api/venv/bin/python
    proxmox_username: "{{ proxmox_user.split('@')[0] }}"
    proxmox_realm: "{{ proxmox_user.split('@')[1] }}"
  tasks:
    - name: Load deployment variables
      import_tasks: tasks/set_fact.yml
     
    - name: Authenticate with Proxmox
      uri:
        url: "https://{{ proxmox_ip }}:8006/api2/json/access/ticket"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ proxmox_username }}"
          password: "{{ proxmox_password }}"
          realm: "{{ proxmox_realm }}"
        validate_certs: false
        status_code: 200
      register: auth_response
     
    - name: debug
      debug:
        msg: "auth OK"
      when: auth_response.status == 200

    - name: setup_sdn
      import_tasks: tasks/setup_sdn.yml
     
    - name: enable_firewall
      import_tasks: tasks/setup_firewall.yml
     
    - name: clone_vms
      import_tasks: tasks/clone_vm.yml

    - name: Start cloned VMs
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_ip }}:8006"
        vmid: "{{ client_id }}00{{ item.id }}"
        node: "{{ proxmox_node }}"
        state: started
        timeout: 180
      loop: "{{ templates }}"
