- name: run_ovpn_script
  command: "/bin/bash /opt/deployment_api/ovpn_scripts/deploy_user_ovpn.sh {{ client_id }} {{ public_ip }}"
  register: script_result
  changed_when: script_result.rc != 0
  failed_when: script_result.rc != 0