---
- name: init_playbook
  hosts: proxmox_node
  gather_facts: yes
  become: yes
  
  tasks:
  # Deploy SDN on the Proxmox node
    - name: deploy_sdn
      import_tasks: tasks/proxmox/deploy_sdn.yml
      vars:
        sdn_name: "{{ sdn_corenet_name }}"
        sdn_network: "{{ sdn_corenet_network }}"
        sdn_gateway: "{{ sdn_corenet_gateway }}"
      
  # Download the Alpine template 
    - name: download_template
      import_tasks: tasks/proxmox/download_template.yml
      vars:
        template_name: "{{ template_alpine_name }}"

  # Deploy the Core container
    - name: deploy_core_container
      import_tasks: tasks/proxmox/deploy_container.yml
      vars:
        container_id: "{{ container_core_id }}"
        container_name: "{{ container_core_name }}"
        container_memory: "{{ container_core_memory }}"
        container_cores: "{{ container_core_cores }}"
        container_ip: "{{ container_core_ip }}"
        template_name: "{{ template_alpine_name }}"
        enable_tun: true

  # Deploy ansible on the Core container
    - name: install_ansible
      import_tasks: tasks/remote/deploy_ansible.yml
      vars:
        container_id: "{{ container_core_id }}"

  # Run the Docker playbook on the Core container
    - name: run_docker_install
      import_tasks: tasks/remote/run_playbook.yml
      vars:
        playbook_path: "remote_playbook/deploy_vpn.yml"  
        container_id: "{{ container_core_id }}"
