---
- name: init_playbook
  hosts: proxmox_node
  gather_facts: yes
  become: yes
  
  tasks:

  # Deploy SDN on the Proxmox node
    - name: deploy_sdn
      import_tasks: tasks/proxmox/deploy_sdn.yml
      vars:
        sdn_name: "{{ sdn_corenet_name }}"
        sdn_network: "{{ sdn_corenet_network }}"
        sdn_gateway: "{{ sdn_corenet_gateway }}"
      
  # Download the Alpine template 
    - name: download_template
      import_tasks: tasks/proxmox/download_template.yml
      vars:
        template_name: "{{ template_alpine_name }}"

  # Deploy the VPN container
    - name: deploy_vpn_container
      import_tasks: tasks/proxmox/deploy_container.yml
      vars:
        container_id: "{{ container_vpn_id }}"
        container_name: "{{ container_vpn_name }}"
        container_memory: "{{ container_vpn_memory }}"
        container_cores: "{{ container_vpn_cores }}"
        container_ip: "{{ container_vpn_ip }}"
        template_name: "{{ template_alpine_name }}"
        container_size: 8
        enable_tun: true

  # Deploy ansible on the VPN container
    - name: install_requirements
      import_tasks: tasks/core_software/install_requirements.yml
      delegate_to: vpn_ct 

  # Deploy the Deployment API on the VPN container (delegated to vpn_ct)
    - name: deploy_deployment_api
      import_tasks: tasks/core_software/deploy_deployment_api.yml
      delegate_to: vpn_ct 

  # Deploy SDN demo
    - name: deploy_sdn_demo
      import_tasks: tasks/proxmox/deploy_sdn.yml
      vars:
        sdn_name: "cust100"
        sdn_network: "10.100.0.0/16"
        sdn_gateway: "10.100.0.254"
