---
- name: init_deploy
  hosts: proxmox_node
  gather_facts: yes
  become: yes
  
  tasks:
  # Deploy SDN on the Proxmox node
    - name: deploy_sdn
      import_tasks: tasks/proxmox/deploy_sdn.yml
      vars:
        sdn_name: "{{ sdn_corenet_name }}"
        sdn_network: "{{ sdn_corenet_network }}"
        sdn_gateway: "{{ sdn_corenet_gateway }}"
      
  # Download the Alpine template 
    - name: download_template
      import_tasks: tasks/proxmox/download_template.yml
      vars:
        template_name: "{{ template_alpine_name }}"

  # Deploy the OpenVPN container
    - name: deploy_openvpn_container
      import_tasks: tasks/proxmox/deploy_container.yml
      vars:
        container_id: "{{ container_openvpn_id }}"
        container_name: "{{ container_openvpn_name }}"
        container_memory: "{{ container_openvpn_memory }}"
        container_cores: "{{ container_openvpn_cores }}"
        container_ip: "{{ container_openvpn_ip }}"
        template_name: "{{ template_alpine_name }}"
        enable_tun: true