---
- name: install_openvpn
  hosts: proxmox_node
  gather_facts: yes
  become: yes
  
  tasks:
  - name: install_openvpn_easyrsa
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "apk add openvpn easy-rsa --update-cache"
      container_id: "{{ container_openvpn_id }}"

  - name: create_easy_rsa_directory
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "mkdir -p /etc/openvpn/easy-rsa"
      container_id: "{{ container_openvpn_id }}"

  - name: copy_easy_rsa_files
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "cp -r /usr/share/easy-rsa/* /etc/openvpn/easy-rsa/"
      container_id: "{{ container_openvpn_id }}"

  - name: initialize_pki
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "cd /etc/openvpn/easy-rsa && ./easyrsa init-pki"
      container_id: "{{ container_openvpn_id }}"

  - name: create_vars_file
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "touch /etc/openvpn/easy-rsa/vars"
      container_id: "{{ container_openvpn_id }}"

  - name: set_country_vars
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "bash -c 'echo \"set_var EASYRSA_REQ_COUNTRY \"US\"\" >> /etc/openvpn/easy-rsa/vars'"
      container_id: "{{ container_openvpn_id }}"

  - name: set_province_vars
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "bash -c 'echo \"set_var EASYRSA_REQ_PROVINCE \"California\"\" >> /etc/openvpn/easy-rsa/vars'"
      container_id: "{{ container_openvpn_id }}"

  - name: set_city_vars
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "bash -c 'echo \"set_var EASYRSA_REQ_CITY \"San Francisco\"\" >> /etc/openvpn/easy-rsa/vars'"
      container_id: "{{ container_openvpn_id }}"

  - name: set_organization_vars
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "bash -c 'echo \"set_var EASYRSA_REQ_ORG \"MyOrg\"\" >> /etc/openvpn/easy-rsa/vars'"
      container_id: "{{ container_openvpn_id }}"

  - name: set_email_vars
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "bash -c 'echo \"set_var EASYRSA_REQ_EMAIL \"email@example.com\"\" >> /etc/openvpn/easy-rsa/vars'"
      container_id: "{{ container_openvpn_id }}"

  - name: set_organizational_unit_vars
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "bash -c 'echo \"set_var EASYRSA_REQ_OU \"MyOrgUnit\"\" >> /etc/openvpn/easy-rsa/vars'"
      container_id: "{{ container_openvpn_id }}"

  - name: build_ca_certificate
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "cd /etc/openvpn/easy-rsa && EASYRSA_BATCH=1 ./easyrsa build-ca nopass"
      container_id: "{{ container_openvpn_id }}"

  - name: generate_server_certificate_request
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "cd /etc/openvpn/easy-rsa && EASYRSA_BATCH=1 ./easyrsa gen-req server nopass"
      container_id: "{{ container_openvpn_id }}"

  - name: sign_server_certificate
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "cd /etc/openvpn/easy-rsa && EASYRSA_BATCH=1 ./easyrsa sign-req server server"
      container_id: "{{ container_openvpn_id }}"

  - name: generate_dh_parameters
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "cd /etc/openvpn/easy-rsa && ./easyrsa gen-dh"
      container_id: "{{ container_openvpn_id }}"

  - name: generate_tls_auth_key
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "cd /etc/openvpn/easy-rsa && openvpn --genkey --secret ta.key"
      container_id: "{{ container_openvpn_id }}"

  - name: create_openvpn_directory
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "mkdir -p /etc/openvpn"
      container_id: "{{ container_openvpn_id }}"

  - name: start_openvpn_service
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "rc-service openvpn start"
      container_id: "{{ container_openvpn_id }}"

  - name: enable_openvpn_service
    include_tasks: tasks/proxmox/exec_container.yml
    vars:
      command: "rc-update add openvpn default"
      container_id: "{{ container_openvpn_id }}"