---
- name: init_playbook
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
  
    # Dynamically add the web container to inventory with SSH args
    - name: add_web_container_to_inventory
      add_host:
        name: "{{ container_web_ip }}"
        groups: web_containers
        ansible_ssh_common_args: "-o ProxyJump=root@{{ ansible_default_ipv4.address }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_ssh_private_key_file: "./assets/ssh_key/id_rsa"
        ansible_user: root

    - name: install_docker
      import_tasks: tasks/core_software/install_docker.yml
      delegate_to: "{{ container_web_ip }}"
          