### Required variables:
# dest_ip
# port_start
# port_end
# protocol

- name: apply_bash
  ansible.builtin.shell: |
    #!/bin/bash

    TARGET_IP="{{ dest_ip }}"
    START_PORT="{{ port_start }}"
    END_PORT="{{ port_end }}"
    PROTOCOL="{{ protocol }}"

    sudo iptables -F
    sudo iptables -X
    sudo iptables -t nat -F
    sudo iptables -t nat -X
    sudo iptables -t mangle -F
    sudo iptables -t mangle -X
    sudo iptables -P INPUT ACCEPT
    sudo iptables -P FORWARD ACCEPT
    sudo iptables -P OUTPUT ACCEPT

    for port in $(seq $START_PORT $END_PORT); do
        sudo iptables -A INPUT -p $PROTOCOL --dport $port -j ACCEPT
        sudo iptables -A OUTPUT -p $PROTOCOL --sport $port -j ACCEPT
    done

    for port in $(seq $START_PORT $END_PORT); do
        sudo iptables -t nat -A PREROUTING -p $PROTOCOL --dport $port -j DNAT --to-destination $TARGET_IP:$port
        sudo iptables -t nat -A POSTROUTING -d $TARGET_IP -p $PROTOCOL --dport $port -j MASQUERADE
    done

    for port in $(seq $START_PORT $END_PORT); do
        sudo iptables -A FORWARD -p $PROTOCOL -d $TARGET_IP --dport $port -j ACCEPT
        sudo iptables -A FORWARD -p $PROTOCOL -s $TARGET_IP --sport $port -j ACCEPT
    done

    iptables-save
  args:
    executable: /bin/bash
