---
- name: Create Template WinSRV
  hosts: proxmox_node
  gather_facts: no

  tasks:

  # Deploy windows server 2012
    - name: deploy_winsrv_2012
      import_tasks: tasks/windows/deploy_winsrv.yml
      vars:
        vm_id: "{{ vm_id_2012 }}"
        iso_file: "{{ vm_iso_2012 }}"
        vm_name: "{{ vm_name_2012 }}"
        storage_name: "local"
        iso_dir: "/var/lib/vz/template/iso"
        provision_iso_name: "{{ vm_name }}provision.iso"
        provision_dir: "/var/lib/vz/template/provision_winsrv"
        vm_memory: 1024  
        vm_cores: 1
        vm_sockets: 1
        drive_size_gb: 14
        format: "qcow2"
        vm_os_type: "win8"  
        agent: 1
  
 

