---
- name: Create Template WinSRV
  hosts: proxmox_node
  gather_facts: no

  tasks:

  # # Check if the template with ID 111 exists
  # - name: check if template with ID 111 exists
  #   import_tasks: tasks/windows/check_template.yml
  #   vars:
  #     vms:
  #       - {vm_id: "{{ vm_id_2012 }}"}
  #       - {vm_id: "{{ vm_id_2012 | int +1}}"}
  #       - {vm_id: "{{ vm_id_2012 | int +2}}"}

  # # Verify if ISO exists
  # - name: verify if iso exists
  #   import_tasks: tasks/windows/verify_iso.yml
  #   when: all_templates_exist == false
  #   vars:
  #     iso_dir: "/var/lib/vz/template/iso"

  # Deploy windows server 2012
  - name: deploy_winsrv_2012
    import_tasks: tasks/windows/deploy_winsrv.yml
    #when: all_templates_exist == false
    vars:
      vm_id: "{{ vm_id_2012 }}"
      vm_name: "{{ vm_name_2012 }}"
      vms: 
        - { vm_id: "{{ vm_id_2012 }}", vm_name: "{{ vm_name_2012 }}01", storage_name: "local" }
        - { vm_id: "{{ vm_id_2012 | int + 1 }}", vm_name: "{{ vm_name_2012 }}02", storage_name: "local" }
        - { vm_id: "{{ vm_id_2012 | int + 2 }}", vm_name: "{{ vm_name_2012 }}03", storage_name: "local" }
      iso_file: "winsrv2012.iso"
      storage_name: "local"
      iso_dir: "/var/lib/vz/template/iso"
      provision_iso_name: "{{ vm_name }}provision.iso"
      provision_dir: "/var/lib/vz/template/provision_winsrv"
      vm_memory: 4096
      vm_cores: 4
      vm_sockets: 1
      drive_size_gb: 14
      format: "qcow2"
      vm_os_type: "win8"  
      agent: 1
      node: "{{ node_name }}"
